In [1]:
import pandas as pd
resampled_data = pd.read_csv('./resampled_data.csv')
print(resampled_data)

               0         1          2          3           11  Label
0        236.850  1.158000   7.310800  -2.397800  3123.396000    0.0
1        165.080  1.543900  -6.630700 -10.276000  3123.393000    0.0
2        308.630  2.573200  -5.157200 -19.525000  3123.390000    0.0
3        236.850  0.643310  -1.076800 -27.289000  3123.387000    0.0
4        251.210 -2.573200   1.870200 -33.569000  3123.384000    0.0
...          ...       ...        ...        ...          ...    ...
1876285 -143.550 -1.676643 -14.595932  -6.265013   155.227624    2.0
1876286  215.320  0.836029  -2.663520   4.739952   119.890370    2.0
1876287  -43.064 -0.097580   0.411372   1.534155   139.040769    2.0
1876288  -71.774  2.519766 -36.351514  -0.021330   150.776813    2.0
1876289  272.740  1.292225   0.339923   3.269927   142.629638    2.0

[1876290 rows x 6 columns]


Dividing data into 3 regions A, B, C.

In [2]:
class_00_data = resampled_data[resampled_data['Label'] == 0.0]
class_01_data = resampled_data[resampled_data['Label'] == 1.0]
class_02_data = resampled_data[resampled_data['Label'] == 2.0]

Importing original data files of W8

In [3]:
import pandas as pd
class_01_data_path = "./class1.csv"

class_02_data_path = "./class2.csv"

class_03_data_path = "./class3.csv"

In [4]:
import numpy as np

# Feature Extraction function - Root Mean Square (RMS)
def rms(data):
    '''RMS features'''
    data = np.asarray(data)
    Rms = pd.DataFrame(np.sqrt(np.mean(data**2, axis=1)))
    return Rms

# Feature Extraction function - Mean
def mean(data):
    '''Mean features'''
    data = np.asarray(np.absolute(data))
    M = pd.DataFrame(np.mean(data, axis=1))
    return M

# Feature Extraction function - Standard Deviation
def std(data):
    '''Standard Deviation features'''
    data = np.asarray(data)
    stdev = pd.DataFrame(np.std(data, axis=1))
    return stdev

# Feature Extraction function - Kurtosis
def kurtosis(data):
    '''Kurtosis features'''
    data = pd.DataFrame(data)
    kurt = data.kurt(axis=1)
    return kurt

# Feature Extraction function - Skewness
def skew(data):
    '''Skewness features'''
    data = pd.DataFrame(data)
    skw = data.skew(axis=1)
    return skw

# Feature Extraction function - Max Divided by Min
def max_by_min(data):
    '''Maximum divided by Minimum feature'''
    data = np.asarray(data)
    max_min_ratio = np.max(data, axis=1) / np.min(data, axis=1)
    max_min_ratio = pd.DataFrame(max_min_ratio)
    return max_min_ratio

def data_extract(path,index):
    data11 = pd.read_csv(path, usecols=[index], header=None)  # read the csv file
    return data11


In [5]:
#For Unbalanced data, which is not oversampled
data_class1_signal0_ori = data_extract(class_01_data_path,0).dropna(axis=0)
data_class1_signal1_ori = data_extract(class_01_data_path,1).dropna(axis=0)
data_class1_signal2_ori = data_extract(class_01_data_path,2).dropna(axis=0)
data_class1_signal3_ori = data_extract(class_01_data_path,3).dropna(axis=0)

data_class2_signal0_ori = data_extract(class_02_data_path,0).dropna(axis=0)
data_class2_signal1_ori = data_extract(class_02_data_path,1).dropna(axis=0)
data_class2_signal2_ori = data_extract(class_02_data_path,2).dropna(axis=0)
data_class2_signal3_ori = data_extract(class_02_data_path,3).dropna(axis=0)

data_class3_signal0_ori = data_extract(class_03_data_path,0).dropna(axis=0)
data_class3_signal1_ori = data_extract(class_03_data_path,1).dropna(axis=0)
data_class3_signal2_ori = data_extract(class_03_data_path,2).dropna(axis=0)
data_class3_signal3_ori = data_extract(class_03_data_path,3).dropna(axis=0)

#For balanced data, which is oversampled
data_class1_signal0 = class_00_data.iloc[:,0].dropna(axis=0)
data_class1_signal1 = class_00_data.iloc[:,1].dropna(axis=0)
data_class1_signal2 = class_00_data.iloc[:,2].dropna(axis=0)
data_class1_signal3 = class_00_data.iloc[:,3].dropna(axis=0)

data_class2_signal0 = class_01_data.iloc[:,0].dropna(axis=0)
data_class2_signal1 = class_01_data.iloc[:,1].dropna(axis=0)
data_class2_signal2 = class_01_data.iloc[:,2].dropna(axis=0)
data_class2_signal3 = class_01_data.iloc[:,3].dropna(axis=0)

data_class3_signal0 = class_02_data.iloc[:,0].dropna(axis=0)
data_class3_signal1 = class_02_data.iloc[:,1].dropna(axis=0)
data_class3_signal2 = class_02_data.iloc[:,2].dropna(axis=0)
data_class3_signal3 = class_02_data.iloc[:,3].dropna(axis=0)

    


In [6]:
def reshape_data(data, num_columns=20):
    '''Reshape data into multiple columns'''
    data = np.asarray(data)
    num_rows = data.shape[0]
    num_full_chunks = num_rows // num_columns

    # Reshape the data into the desired shape
    reshaped_data = data[:num_full_chunks*num_columns].reshape(-1, num_columns)
    
    return reshaped_data

def NormalizeData(data):  # Normalization (0-1)
    # Find the maximum and minimum values in the input data
    data_max = np.max(data)
    data_min = np.min(data)
    
    # Normalize the data using the formula (data - min) / (max - min)
    normalized_data = (data - data_min) / (data_max - data_min)
    normalized_data=reshape_data(normalized_data)
    # Return the normalized data
    return normalized_data

In [7]:
normalised_10=NormalizeData(data_class1_signal0)
normalised_11=NormalizeData(data_class1_signal1)
normalised_12=NormalizeData(data_class1_signal2)
normalised_13=NormalizeData(data_class1_signal3)

normalised_20=NormalizeData(data_class2_signal0)
normalised_21=NormalizeData(data_class2_signal1)
normalised_22=NormalizeData(data_class2_signal2)
normalised_23=NormalizeData(data_class2_signal3)

normalised_30=NormalizeData(data_class3_signal0)
normalised_31=NormalizeData(data_class3_signal1)
normalised_32=NormalizeData(data_class3_signal2)
normalised_33=NormalizeData(data_class3_signal3)

normalised_10_ori=NormalizeData(data_class1_signal0_ori)
normalised_11_ori=NormalizeData(data_class1_signal1_ori)
normalised_12_ori=NormalizeData(data_class1_signal2_ori)
normalised_13_ori=NormalizeData(data_class1_signal3_ori)

normalised_20_ori=NormalizeData(data_class2_signal0_ori)
normalised_21_ori=NormalizeData(data_class2_signal1_ori)
normalised_22_ori=NormalizeData(data_class2_signal2_ori)
normalised_23_ori=NormalizeData(data_class2_signal3_ori)

normalised_30_ori=NormalizeData(data_class3_signal0_ori)
normalised_31_ori=NormalizeData(data_class3_signal1_ori)
normalised_32_ori=NormalizeData(data_class3_signal2_ori)
normalised_33_ori=NormalizeData(data_class3_signal3_ori)

In [8]:
rms_10 = rms(normalised_10)
rms_11 = rms(normalised_11)
rms_12 = rms(normalised_12)
rms_13 = rms(normalised_13)

rms_20 = rms(normalised_20)
rms_21 = rms(normalised_21)
rms_22 = rms(normalised_22)
rms_23 = rms(normalised_23)

rms_30 = rms(normalised_30)
rms_31 = rms(normalised_31)
rms_32 = rms(normalised_32)
rms_33 = rms(normalised_33)

rms_1=pd.concat([rms_10,rms_20,rms_30],axis=0,ignore_index=True)
rms_2=pd.concat([rms_11,rms_21,rms_31],axis=0,ignore_index=True)
rms_3=pd.concat([rms_12,rms_22,rms_32],axis=0,ignore_index=True)
rms_4=pd.concat([rms_13,rms_23,rms_33],axis=0,ignore_index=True)

rms_10_ori = rms(normalised_10_ori)
rms_11_ori = rms(normalised_11_ori)
rms_12_ori = rms(normalised_12_ori)
rms_13_ori = rms(normalised_13_ori)

rms_20_ori = rms(normalised_20_ori)
rms_21_ori = rms(normalised_21_ori)
rms_22_ori = rms(normalised_22_ori)
rms_23_ori = rms(normalised_23_ori)

rms_30_ori = rms(normalised_30_ori)
rms_31_ori = rms(normalised_31_ori)
rms_32_ori = rms(normalised_32_ori)
rms_33_ori = rms(normalised_33_ori)

rms_1_ori=pd.concat([rms_10_ori,rms_20_ori,rms_30_ori],axis=0,ignore_index=True)
rms_2_ori=pd.concat([rms_11_ori,rms_21_ori,rms_31_ori],axis=0,ignore_index=True)
rms_3_ori=pd.concat([rms_12_ori,rms_22_ori,rms_32_ori],axis=0,ignore_index=True)
rms_4_ori=pd.concat([rms_13_ori,rms_23_ori,rms_33_ori],axis=0,ignore_index=True)


In [9]:
mean_10 = mean(normalised_10)
mean_11 = mean(normalised_11)
mean_12 = mean(normalised_12)
mean_13 = mean(normalised_13)

mean_20 = mean(normalised_20)
mean_21 = mean(normalised_21)
mean_22 = mean(normalised_22)
mean_23 = mean(normalised_23)

mean_30 = mean(normalised_30)
mean_31 = mean(normalised_31)
mean_32 = mean(normalised_32)
mean_33 = mean(normalised_33)

mean_1=pd.concat([mean_10,mean_20,mean_30],axis=0,ignore_index=True)
mean_2=pd.concat([mean_11,mean_21,mean_31],axis=0,ignore_index=True)
mean_3=pd.concat([mean_12,mean_22,mean_32],axis=0,ignore_index=True)
mean_4=pd.concat([mean_13,mean_23,mean_33],axis=0,ignore_index=True)

mean_10_ori = mean(normalised_10_ori)
mean_11_ori = mean(normalised_11_ori)
mean_12_ori = mean(normalised_12_ori)
mean_13_ori = mean(normalised_13_ori)

mean_20_ori = mean(normalised_20_ori)
mean_21_ori = mean(normalised_21_ori)
mean_22_ori = mean(normalised_22_ori)
mean_23_ori = mean(normalised_23_ori)

mean_30_ori = mean(normalised_30_ori)
mean_31_ori = mean(normalised_31_ori)
mean_32_ori = mean(normalised_32_ori)
mean_33_ori = mean(normalised_33_ori)

mean_1_ori=pd.concat([mean_10_ori,mean_20_ori,mean_30_ori],axis=0,ignore_index=True)
mean_2_ori=pd.concat([mean_11_ori,mean_21_ori,mean_31_ori],axis=0,ignore_index=True)
mean_3_ori=pd.concat([mean_12_ori,mean_22_ori,mean_32_ori],axis=0,ignore_index=True)
mean_4_ori=pd.concat([mean_13_ori,mean_23_ori,mean_33_ori],axis=0,ignore_index=True)


In [10]:
std_10= std(normalised_10)
std_11= std(normalised_11)
std_12= std(normalised_12)
std_13= std(normalised_13)

std_20= std(normalised_20)
std_21= std(normalised_21)
std_22= std(normalised_22)
std_23= std(normalised_23)

std_30= std(normalised_30)
std_31= std(normalised_31)
std_32= std(normalised_32)
std_33= std(normalised_33)

std_1=pd.concat([std_10,std_20,std_30],axis=0,ignore_index=True)
std_2=pd.concat([std_11,std_21,std_31],axis=0,ignore_index=True)
std_3=pd.concat([std_12,std_22,std_32],axis=0,ignore_index=True)
std_4=pd.concat([std_13,std_23,std_33],axis=0,ignore_index=True)

std_10_ori = std(normalised_10_ori)
std_11_ori = std(normalised_11_ori)
std_12_ori = std(normalised_12_ori)
std_13_ori = std(normalised_13_ori)

std_20_ori = std(normalised_20_ori)
std_21_ori = std(normalised_21_ori)
std_22_ori = std(normalised_22_ori)
std_23_ori = std(normalised_23_ori)

std_30_ori = std(normalised_30_ori)
std_31_ori = std(normalised_31_ori)
std_32_ori = std(normalised_32_ori)
std_33_ori = std(normalised_33_ori)

std_1_ori=pd.concat([std_10_ori,std_20_ori,std_30_ori],axis=0,ignore_index=True)
std_2_ori=pd.concat([std_11_ori,std_21_ori,std_31_ori],axis=0,ignore_index=True)
std_3_ori=pd.concat([std_12_ori,std_22_ori,std_32_ori],axis=0,ignore_index=True)
std_4_ori=pd.concat([std_13_ori,std_23_ori,std_33_ori],axis=0,ignore_index=True)


In [11]:
kurtosis_10 = kurtosis(normalised_10)
kurtosis_11 = kurtosis(normalised_11)
kurtosis_12 = kurtosis(normalised_12)
kurtosis_13 = kurtosis(normalised_13)

kurtosis_20 = kurtosis(normalised_20)
kurtosis_21 = kurtosis(normalised_21)
kurtosis_22 = kurtosis(normalised_22)
kurtosis_23 = kurtosis(normalised_23)

kurtosis_30 = kurtosis(normalised_30)
kurtosis_31 = kurtosis(normalised_31)
kurtosis_32 = kurtosis(normalised_32)
kurtosis_33 = kurtosis(normalised_33)

kurtosis_1=pd.concat([kurtosis_10,kurtosis_20,kurtosis_30],axis=0,ignore_index=True)
kurtosis_2=pd.concat([kurtosis_11,kurtosis_21,kurtosis_31],axis=0,ignore_index=True)
kurtosis_3=pd.concat([kurtosis_12,kurtosis_22,kurtosis_32],axis=0,ignore_index=True)
kurtosis_4=pd.concat([kurtosis_13,kurtosis_23,kurtosis_33],axis=0,ignore_index=True)

kurtosis_10_ori = kurtosis(normalised_10_ori)
kurtosis_11_ori = kurtosis(normalised_11_ori)
kurtosis_12_ori = kurtosis(normalised_12_ori)
kurtosis_13_ori = kurtosis(normalised_13_ori)

kurtosis_20_ori = kurtosis(normalised_20_ori)
kurtosis_21_ori = kurtosis(normalised_21_ori)
kurtosis_22_ori = kurtosis(normalised_22_ori)
kurtosis_23_ori = kurtosis(normalised_23_ori)

kurtosis_30_ori = kurtosis(normalised_30_ori)
kurtosis_31_ori = kurtosis(normalised_31_ori)
kurtosis_32_ori = kurtosis(normalised_32_ori)
kurtosis_33_ori = kurtosis(normalised_33_ori)

kurtosis_1_ori=pd.concat([kurtosis_10_ori,kurtosis_20_ori,kurtosis_30_ori],axis=0,ignore_index=True)
kurtosis_2_ori=pd.concat([kurtosis_11_ori,kurtosis_21_ori,kurtosis_31_ori],axis=0,ignore_index=True)
kurtosis_3_ori=pd.concat([kurtosis_12_ori,kurtosis_22_ori,kurtosis_32_ori],axis=0,ignore_index=True)
kurtosis_4_ori=pd.concat([kurtosis_13_ori,kurtosis_23_ori,kurtosis_33_ori],axis=0,ignore_index=True)


In [12]:
skew_10= skew(normalised_10)
skew_11= skew(normalised_11)
skew_12= skew(normalised_12)
skew_13= skew(normalised_13)

skew_20= skew(normalised_20)
skew_21= skew(normalised_21)
skew_22= skew(normalised_22)
skew_23= skew(normalised_23)

skew_30= skew(normalised_30)
skew_31= skew(normalised_31)
skew_32= skew(normalised_32)
skew_33= skew(normalised_33)

skew_1=pd.concat([skew_10,skew_20,skew_30],axis=0,ignore_index=True)
skew_2=pd.concat([skew_11,skew_21,skew_31],axis=0,ignore_index=True)    
skew_3=pd.concat([skew_12,skew_22,skew_32],axis=0,ignore_index=True)
skew_4=pd.concat([skew_13,skew_23,skew_33],axis=0,ignore_index=True)

skew_10_ori = skew(normalised_10_ori)
skew_11_ori = skew(normalised_11_ori)
skew_12_ori = skew(normalised_12_ori)
skew_13_ori = skew(normalised_13_ori)

skew_20_ori = skew(normalised_20_ori)
skew_21_ori = skew(normalised_21_ori)
skew_22_ori = skew(normalised_22_ori)
skew_23_ori = skew(normalised_23_ori)

skew_30_ori = skew(normalised_30_ori)
skew_31_ori = skew(normalised_31_ori)
skew_32_ori = skew(normalised_32_ori)
skew_33_ori = skew(normalised_33_ori)

skew_1_ori=pd.concat([skew_10_ori,skew_20_ori,skew_30_ori],axis=0,ignore_index=True)
skew_2_ori=pd.concat([skew_11_ori,skew_21_ori,skew_31_ori],axis=0,ignore_index=True)
skew_3_ori=pd.concat([skew_12_ori,skew_22_ori,skew_32_ori],axis=0,ignore_index=True)
skew_4_ori=pd.concat([skew_13_ori,skew_23_ori,skew_33_ori],axis=0,ignore_index=True)

In [13]:
max_by_min_10= max_by_min(normalised_10)
max_by_min_11= max_by_min(normalised_11)
max_by_min_12= max_by_min(normalised_12)
max_by_min_13= max_by_min(normalised_13)

max_by_min_20= max_by_min(normalised_20)
max_by_min_21= max_by_min(normalised_21)
max_by_min_22= max_by_min(normalised_22)
max_by_min_23= max_by_min(normalised_23)

max_by_min_30= max_by_min(normalised_30)
max_by_min_31= max_by_min(normalised_31)
max_by_min_32= max_by_min(normalised_32)
max_by_min_33= max_by_min(normalised_33)

max_by_min_1=pd.concat([max_by_min_10,max_by_min_20,max_by_min_30],axis=0,ignore_index=True)
max_by_min_2=pd.concat([max_by_min_11,max_by_min_21,max_by_min_31],axis=0,ignore_index=True)
max_by_min_3=pd.concat([max_by_min_12,max_by_min_22,max_by_min_32],axis=0,ignore_index=True)
max_by_min_4=pd.concat([max_by_min_13,max_by_min_23,max_by_min_33],axis=0,ignore_index=True)

max_by_min_10_ori = max_by_min(normalised_10_ori)
max_by_min_11_ori = max_by_min(normalised_11_ori)
max_by_min_12_ori = max_by_min(normalised_12_ori)
max_by_min_13_ori = max_by_min(normalised_13_ori)

max_by_min_20_ori = max_by_min(normalised_20_ori)
max_by_min_21_ori = max_by_min(normalised_21_ori)
max_by_min_22_ori = max_by_min(normalised_22_ori)
max_by_min_23_ori = max_by_min(normalised_23_ori)

max_by_min_30_ori = max_by_min(normalised_30_ori)
max_by_min_31_ori = max_by_min(normalised_31_ori)
max_by_min_32_ori = max_by_min(normalised_32_ori)
max_by_min_33_ori = max_by_min(normalised_33_ori)

max_by_min_1_ori=pd.concat([max_by_min_10_ori,max_by_min_20_ori,max_by_min_30_ori],axis=0,ignore_index=True)
max_by_min_2_ori=pd.concat([max_by_min_11_ori,max_by_min_21_ori,max_by_min_31_ori],axis=0,ignore_index=True)
max_by_min_3_ori=pd.concat([max_by_min_12_ori,max_by_min_22_ori,max_by_min_32_ori],axis=0,ignore_index=True)
max_by_min_4_ori=pd.concat([max_by_min_13_ori,max_by_min_23_ori,max_by_min_33_ori],axis=0,ignore_index=True)


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_23912\2626590613.py:42: RuntimeWarning: divide by zero encountered in divide
  max_min_ratio = np.max(data, axis=1) / np.min(data, axis=1)


In [14]:
# Concatenate features for 1st signal
x_1 = pd.concat([std_1, rms_1, kurtosis_1, skew_1], axis=1, ignore_index=True)
# Concatenate features for 2nd signal
x_2 = pd.concat([std_2, rms_2, kurtosis_2, skew_2], axis=1, ignore_index=True)
# Concatenate features for 3rd signal
x_3 = pd.concat([std_3, rms_3, kurtosis_3, skew_3], axis=1, ignore_index=True)
# Concatenate features for 4th signal
x_4 = pd.concat([std_4, rms_4, kurtosis_4, skew_4], axis=1, ignore_index=True)

pd.DataFrame(x_1).to_csv("./new_features/features_w8_1_signal.csv", index=None, header=False)
pd.DataFrame(x_2).to_csv("./new_features/features_w8_2_signal.csv", index=None, header=False)
pd.DataFrame(x_3).to_csv("./new_features/features_w8_3_signal.csv", index=None, header=False)
pd.DataFrame(x_4).to_csv("./new_features/features_w8_4_signal.csv", index=None, header=False)

# Create labels for Class 1 signals
y_1 = np.full((int(len(mean_10)), 1), 'A')

# Create labels for Class 2 signals
y_2 = np.full((int(len(mean_20)), 1), 'B')

# Create labels for Class 3 signals
y_3 = np.full((int(len(mean_30)), 1), 'C')

# Concatenate all labels into a single array
y = np.concatenate((y_1, y_2, y_3), axis=None)

# Display the shape of the resulting array
y.shape

# Save the label data to a CSV file
y_label = pd.DataFrame(y).to_csv("./new_features/labels_w8.csv", index=None, header=False)

# Repeat the same process for additional label creation if needed


In [15]:
# Concatenate features for 1st signal
x_1_ori = pd.concat([ std_1_ori, rms_1_ori, kurtosis_1_ori, skew_1_ori], axis=1, ignore_index=True)
# Concatenate features for 2nd signal
x_2_ori = pd.concat([ std_2_ori, rms_2_ori, kurtosis_2_ori, skew_2_ori], axis=1, ignore_index=True)
# Concatenate features for 3rd signal
x_3_ori = pd.concat([ std_3_ori, rms_3_ori, kurtosis_3_ori, skew_3_ori], axis=1, ignore_index=True)
# Concatenate features for 4th signal
x_4_ori = pd.concat([ std_4_ori, rms_4_ori, kurtosis_4_ori, skew_4_ori], axis=1, ignore_index=True)

pd.DataFrame(x_1_ori).to_csv("./new_features/features_w8_1_signal_ori.csv", index=None, header=False)
pd.DataFrame(x_2_ori).to_csv("./new_features/features_w8_2_signal_ori.csv", index=None, header=False)
pd.DataFrame(x_3_ori).to_csv("./new_features/features_w8_3_signal_ori.csv", index=None, header=False)
pd.DataFrame(x_4_ori).to_csv("./new_features/features_w8_4_signal_ori.csv", index=None, header=False)

# Repeat the same process for additional label creation if needed

In [16]:
# For Training and testing
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline 
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

has_infinity_1 = np.any(np.isinf(x_1))
if has_infinity_1:
    # Replace Infinity with NaN
    x_1[np.isinf(x_1)] = np.nan

has_infinity_2 = np.any(np.isinf(x_2))
if has_infinity_2:
    # Replace Infinity with NaN
    x_2[np.isinf(x_2)] = np.nan
    
has_infinity_3 = np.any(np.isinf(x_3))
if has_infinity_3:
    # Replace Infinity with NaN
    x_3[np.isinf(x_3)] = np.nan
    
has_infinity_4 = np.any(np.isinf(x_4))
if has_infinity_4:
    # Replace Infinity with NaN
    x_4[np.isinf(x_4)] = np.nan


# # Load label data
# y = pd.read_csv("./new_features/labels_w8.csv", header=None).values.flatten()

X1_train, X1_test, y1_train, y1_test = train_test_split(
    x_1, y, test_size=0.2, random_state=42, shuffle=True
)

X2_train, X2_test, y2_train, y2_test = train_test_split(
    x_2, y, test_size=0.2, random_state=42, shuffle=True
)

X3_train, X3_test, y3_train, y3_test = train_test_split(
    x_3, y, test_size=0.2, random_state=42, shuffle=True
) 

X4_train, X4_test, y4_train, y4_test = train_test_split(
    x_4, y, test_size=0.2, random_state=42, shuffle=True
)

imputer = SimpleImputer(strategy='mean')
svm = SVC(random_state = 1)
pipeline1 = Pipeline([('imputer', imputer), ('svm', svm)])
pipeline2 = Pipeline([('imputer', imputer), ('svm', svm)])
pipeline3 = Pipeline([('imputer', imputer), ('svm', svm)])
pipeline4 = Pipeline([('imputer', imputer), ('svm', svm)])
pipeline1.fit(X1_train,y1_train)


Pipeline(steps=[('imputer', SimpleImputer()), ('svm', SVC(random_state=1))])

In [17]:
import pickle
def make_model_and_save_as_pickle(model,name):
    pkl_filename=name
    with open(pkl_filename,'wb') as file:
        pickle.dump(model,file)

In [18]:
make_model_and_save_as_pickle(pipeline1,r'./model_pickle_files/svm/axial.pkl')

In [19]:

pipeline2.fit(X2_train,y2_train)


Pipeline(steps=[('imputer', SimpleImputer()), ('svm', SVC(random_state=1))])

In [20]:
make_model_and_save_as_pickle(pipeline2,'./model_pickle_files/svm/bending_moment.pkl')

In [21]:

pipeline3.fit(X3_train,y3_train)


Pipeline(steps=[('imputer', SimpleImputer()), ('svm', SVC(random_state=1))])

In [22]:
make_model_and_save_as_pickle(pipeline3,'./model_pickle_files/svm/channel2.pkl')

In [23]:

pipeline4.fit(X4_train,y4_train)

#printing confusion matrix of all 4 pipelines models

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

y1_pred = pipeline1.predict(X1_test)


In [24]:
make_model_and_save_as_pickle(pipeline4,'./model_pickle_files/svm/spindle_power.pkl')

In [25]:
has_infinity_1 = np.any(np.isinf(x_1_ori))
if has_infinity_1:
    # Replace Infinity with NaN
    x_1_ori[np.isinf(x_1_ori)] = np.nan

has_infinity_2 = np.any(np.isinf(x_2_ori))
if has_infinity_2:
    # Replace Infinity with NaN
    x_2_ori[np.isinf(x_2_ori)] = np.nan
    
has_infinity_3 = np.any(np.isinf(x_3_ori))
if has_infinity_3:
    # Replace Infinity with NaN
    x_3_ori[np.isinf(x_3_ori)] = np.nan
    
has_infinity_4 = np.any(np.isinf(x_4_ori))
if has_infinity_4:
    # Replace Infinity with NaN
    x_4_ori[np.isinf(x_4_ori)] = np.nan
y1_pred_ori=pipeline1.predict(x_1_ori)

In [26]:

y2_pred = pipeline2.predict(X2_test)


In [27]:
y2_pred_ori = pipeline2.predict(x_2_ori)

In [28]:

y3_pred = pipeline3.predict(X3_test)


In [29]:
y3_pred_ori=pipeline3.predict(x_3_ori)

In [30]:

y4_pred = pipeline4.predict(X4_test)


In [31]:
y4_pred_ori=pipeline4.predict(x_4_ori)

In [32]:
# Results on oversampled Data

print("Confusion Matrix for 1st signal:")
print(confusion_matrix(y1_test, y1_pred))
print("Accuracy for 1st signal:")
print(accuracy_score(y1_test, y1_pred))
print("Classification Report for 1st signal:")
print(classification_report(y1_test, y1_pred))
print("F1 Score for 1st signal:")
print(f1_score(y1_test, y1_pred, average='weighted'))



Confusion Matrix for 1st signal:
[[2733 3416   46]
 [3214 3114   31]
 [2884 3267   58]]
Accuracy for 1st signal:
0.31471513084261576
Classification Report for 1st signal:
              precision    recall  f1-score   support

           A       0.31      0.44      0.36      6195
           B       0.32      0.49      0.39      6359
           C       0.43      0.01      0.02      6209

    accuracy                           0.31     18763
   macro avg       0.35      0.31      0.26     18763
weighted avg       0.35      0.31      0.26     18763

F1 Score for 1st signal:
0.25680453832202643


In [33]:
# Results on original Data
# Create labels for Class 1 signals
y_1_ori = np.full((int(len(mean_10_ori)), 1), 'A')

# Create labels for Class 2 signals
y_2_ori = np.full((int(len(mean_20_ori)), 1), 'B')

# Create labels for Class 3 signals
y_3_ori = np.full((int(len(mean_30_ori)), 1), 'C')

# Concatenate all labels into a single array
y_ori = np.concatenate((y_1_ori, y_2_ori, y_3_ori), axis=None)
print("Confusion Matrix for 1st signal:")
print(confusion_matrix(y_ori, y1_pred_ori))
print("Accuracy for 1st signal:")
print(accuracy_score(y_ori, y1_pred_ori))
print("Classification Report for 1st signal:")
print(classification_report(y_ori, y1_pred_ori))
print("F1 Score for 1st signal:")
print(f1_score(y_ori, y1_pred_ori, average='weighted'))



Confusion Matrix for 1st signal:
[[ 7519 10034   133]
 [15824 15292   155]
 [ 1426  1633    39]]
Accuracy for 1st signal:
0.43895879358370954
Classification Report for 1st signal:
              precision    recall  f1-score   support

           A       0.30      0.43      0.35     17686
           B       0.57      0.49      0.53     31271
           C       0.12      0.01      0.02      3098

    accuracy                           0.44     52055
   macro avg       0.33      0.31      0.30     52055
weighted avg       0.45      0.44      0.44     52055

F1 Score for 1st signal:
0.4372203949929476


In [34]:
#oversampled data results
print("Confusion Matrix for 2nd signal:")
print(confusion_matrix(y2_test, y2_pred))
print("Accuracy for 2nd signal:")
print(accuracy_score(y2_test, y2_pred))
print("Classification Report for 2nd signal:")
print(classification_report(y2_test, y2_pred))
print("F1 Score for 2nd signal:")
print(f1_score(y2_test, y2_pred, average='weighted'))



Confusion Matrix for 2nd signal:
[[2168 4020    7]
 [1961 4393    5]
 [3122 3075   12]]
Accuracy for 2nd signal:
0.35031711346799554
Classification Report for 2nd signal:
              precision    recall  f1-score   support

           A       0.30      0.35      0.32      6195
           B       0.38      0.69      0.49      6359
           C       0.50      0.00      0.00      6209

    accuracy                           0.35     18763
   macro avg       0.39      0.35      0.27     18763
weighted avg       0.39      0.35      0.27     18763

F1 Score for 2nd signal:
0.2745908765098469


In [35]:

#original data results
print("Confusion Matrix for 2nd signal:")
print(confusion_matrix(y_ori, y2_pred_ori))
print("Accuracy for 2nd signal:")
print(accuracy_score(y_ori, y2_pred_ori))
print("Classification Report for 2nd signal:")
print(classification_report(y_ori, y2_pred_ori))
print("F1 Score for 2nd signal:")
print(f1_score(y_ori, y2_pred_ori, average='weighted'))



Confusion Matrix for 2nd signal:
[[ 5688 11988    10]
 [ 9914 21344    13]
 [ 1376  1719     3]]
Accuracy for 2nd signal:
0.5193545288637018
Classification Report for 2nd signal:
              precision    recall  f1-score   support

           A       0.34      0.32      0.33     17686
           B       0.61      0.68      0.64     31271
           C       0.12      0.00      0.00      3098

    accuracy                           0.52     52055
   macro avg       0.35      0.34      0.32     52055
weighted avg       0.49      0.52      0.50     52055

F1 Score for 2nd signal:
0.49827358347447076


In [36]:

#oversampled data results

print("Confusion Matrix for 3rd signal:")
print(confusion_matrix(y3_test, y3_pred))
print("Accuracy for 3rd signal:")
print(accuracy_score(y3_test, y3_pred))
print("Classification Report for 3rd signal:")
print(classification_report(y3_test, y3_pred))
print("F1 Score for 3rd signal:")
print(f1_score(y3_test, y3_pred, average='weighted'))




Confusion Matrix for 3rd signal:
[[1887 4261   47]
 [1484 4708  167]
 [1067 5124   18]]
Accuracy for 3rd signal:
0.35244896871502424
Classification Report for 3rd signal:
              precision    recall  f1-score   support

           A       0.43      0.30      0.35      6195
           B       0.33      0.74      0.46      6359
           C       0.08      0.00      0.01      6209

    accuracy                           0.35     18763
   macro avg       0.28      0.35      0.27     18763
weighted avg       0.28      0.35      0.28     18763

F1 Score for 3rd signal:
0.2750713634538262


In [37]:

#original data results
print("Confusion Matrix for 3rd signal:")
print(confusion_matrix(y_ori, y3_pred_ori))
print("Accuracy for 3rd signal:")
print(accuracy_score(y_ori, y3_pred_ori))
print("Classification Report for 3rd signal:")
print(classification_report(y_ori, y3_pred_ori))
print("F1 Score for 3rd signal:")
print(f1_score(y_ori, y3_pred_ori, average='weighted'))


Confusion Matrix for 3rd signal:
[[ 3414 13937   335]
 [ 7203 23271   797]
 [  275  2786    37]]
Accuracy for 3rd signal:
0.5133416578618769
Classification Report for 3rd signal:
              precision    recall  f1-score   support

           A       0.31      0.19      0.24     17686
           B       0.58      0.74      0.65     31271
           C       0.03      0.01      0.02      3098

    accuracy                           0.51     52055
   macro avg       0.31      0.32      0.30     52055
weighted avg       0.46      0.51      0.47     52055

F1 Score for 3rd signal:
0.4745352256789499


In [38]:
#oversampled data
print("Confusion Matrix for 4th signal:")
print(confusion_matrix(y4_test, y4_pred))
print("Accuracy for 4th signal:")
print(accuracy_score(y4_test, y4_pred))
print("Classification Report for 4th signal:")
print(classification_report(y4_test, y4_pred))
print("F1 Score for 4th signal:")
print(f1_score(y4_test, y4_pred, average='weighted'))



Confusion Matrix for 4th signal:
[[3303 2007  885]
 [1275 4348  736]
 [ 316  522 5371]]
Accuracy for 4th signal:
0.694025475670202
Classification Report for 4th signal:
              precision    recall  f1-score   support

           A       0.67      0.53      0.60      6195
           B       0.63      0.68      0.66      6359
           C       0.77      0.87      0.81      6209

    accuracy                           0.69     18763
   macro avg       0.69      0.69      0.69     18763
weighted avg       0.69      0.69      0.69     18763

F1 Score for 4th signal:
0.6886310094886651


In [39]:
#original data
print("Confusion Matrix for 4th signal:")
print(confusion_matrix(y_ori, y4_pred_ori))
print("Accuracy for 4th signal:")
print(accuracy_score(y_ori, y4_pred_ori))
print("Classification Report for 4th signal:")
print(classification_report(y_ori, y4_pred_ori))
print("F1 Score for 4th signal:")
print(f1_score(y_ori, y4_pred_ori, average='weighted'))



Confusion Matrix for 4th signal:
[[ 6417  8162  3107]
 [ 6091 21328  3852]
 [  136   789  2173]]
Accuracy for 4th signal:
0.574738257612141
Classification Report for 4th signal:
              precision    recall  f1-score   support

           A       0.51      0.36      0.42     17686
           B       0.70      0.68      0.69     31271
           C       0.24      0.70      0.36      3098

    accuracy                           0.57     52055
   macro avg       0.48      0.58      0.49     52055
weighted avg       0.61      0.57      0.58     52055

F1 Score for 4th signal:
0.581238773763368


In [40]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


# instantiate the model
knn1 = KNeighborsClassifier(n_neighbors=3)
knn2 = KNeighborsClassifier(n_neighbors=3)
knn3 = KNeighborsClassifier(n_neighbors=3)
knn4 = KNeighborsClassifier(n_neighbors=3)



In [41]:
# fit the model to the training set
knn1.fit(X1_train, y1_train)

KNeighborsClassifier(n_neighbors=3)

In [42]:
knn2.fit(X2_train, y2_train)

KNeighborsClassifier(n_neighbors=3)

In [43]:
knn3.fit(X3_train, y3_train)

KNeighborsClassifier(n_neighbors=3)

In [44]:
knn4.fit(X4_train, y4_train)

KNeighborsClassifier(n_neighbors=3)

In [45]:
make_model_and_save_as_pickle(knn1,'./model_pickle_files/knn/axial_force.pkl')
make_model_and_save_as_pickle(knn2,'./model_pickle_files/knn/bending_moment.pkl')
make_model_and_save_as_pickle(knn3,'./model_pickle_files/knn/channel2.pkl')
make_model_and_save_as_pickle(knn4,'./model_pickle_files/knn/spindle_power.pkl')

In [46]:
y1_pred = knn1.predict(X1_test)
y1_pred_ori=knn1.predict(x_1_ori)

In [47]:
y2_pred = knn2.predict(X2_test)
y2_pred_ori=knn2.predict(x_2_ori)

In [48]:
y3_pred = knn3.predict(X3_test)
y3_pred_ori=knn3.predict(x_3_ori)

In [49]:
y4_pred = knn1.predict(X4_test)
y4_pred_ori=knn1.predict(x_4_ori)

In [50]:
def printResults(ori,pred):
    #original data
    print("Confusion Matrix for this signal:")
    print(confusion_matrix(ori, pred))
    print("Accuracy for this signal:")
    print(accuracy_score(ori, pred))
    print("Classification Report for this signal:")
    print(classification_report(ori, pred))
    print("F1 Score for this signal:")
    print(f1_score(ori, pred, average='weighted'))

In [51]:
printResults(y1_test,y1_pred)

Confusion Matrix for this signal:
[[3014 1311 1870]
 [2308 2855 1196]
 [2879 1068 2262]]
Accuracy for this signal:
0.4333528753397644
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.37      0.49      0.42      6195
           B       0.55      0.45      0.49      6359
           C       0.42      0.36      0.39      6209

    accuracy                           0.43     18763
   macro avg       0.45      0.43      0.43     18763
weighted avg       0.45      0.43      0.43     18763

F1 Score for this signal:
0.434941239458829


In [52]:
printResults(y_ori,y1_pred_ori)

Confusion Matrix for this signal:
[[12400  2519  2767]
 [ 8737 19158  3376]
 [ 1034   328  1736]]
Accuracy for this signal:
0.6395927384497166
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.56      0.70      0.62     17686
           B       0.87      0.61      0.72     31271
           C       0.22      0.56      0.32      3098

    accuracy                           0.64     52055
   macro avg       0.55      0.62      0.55     52055
weighted avg       0.73      0.64      0.66     52055

F1 Score for this signal:
0.662272537794945


In [53]:
printResults(y2_test,y2_pred)

Confusion Matrix for this signal:
[[3112 2177  906]
 [2996 2280 1083]
 [1395  774 4040]]
Accuracy for this signal:
0.5026914672493737
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.41      0.50      0.45      6195
           B       0.44      0.36      0.39      6359
           C       0.67      0.65      0.66      6209

    accuracy                           0.50     18763
   macro avg       0.51      0.50      0.50     18763
weighted avg       0.51      0.50      0.50     18763

F1 Score for this signal:
0.5018474250432754


In [54]:
printResults(y_ori,y2_pred_ori)

Confusion Matrix for this signal:
[[11896  3783  2007]
 [ 9972 17696  3603]
 [  613   270  2215]]
Accuracy for this signal:
0.6110267985784267
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.53      0.67      0.59     17686
           B       0.81      0.57      0.67     31271
           C       0.28      0.71      0.41      3098

    accuracy                           0.61     52055
   macro avg       0.54      0.65      0.56     52055
weighted avg       0.69      0.61      0.63     52055

F1 Score for this signal:
0.626383842100348


In [55]:
printResults(y3_test,y3_pred)

Confusion Matrix for this signal:
[[3484 1307 1404]
 [2025 3841  493]
 [1413  360 4436]]
Accuracy for this signal:
0.6268187390076214
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.50      0.56      0.53      6195
           B       0.70      0.60      0.65      6359
           C       0.70      0.71      0.71      6209

    accuracy                           0.63     18763
   macro avg       0.63      0.63      0.63     18763
weighted avg       0.63      0.63      0.63     18763

F1 Score for this signal:
0.6288700035548258


In [56]:
printResults(y_ori,y3_pred_ori)

Confusion Matrix for this signal:
[[12532  2476  2678]
 [ 6747 23100  1424]
 [  620   184  2294]]
Accuracy for this signal:
0.7285755450965326
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.63      0.71      0.67     17686
           B       0.90      0.74      0.81     31271
           C       0.36      0.74      0.48      3098

    accuracy                           0.73     52055
   macro avg       0.63      0.73      0.65     52055
weighted avg       0.77      0.73      0.74     52055

F1 Score for this signal:
0.7419733973584963


In [57]:
printResults(y4_test,y4_pred)

Confusion Matrix for this signal:
[[2399  911 2885]
 [2750  931 2678]
 [3220  818 2171]]
Accuracy for this signal:
0.2931833928476256
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.29      0.39      0.33      6195
           B       0.35      0.15      0.21      6359
           C       0.28      0.35      0.31      6209

    accuracy                           0.29     18763
   macro avg       0.31      0.29      0.28     18763
weighted avg       0.31      0.29      0.28     18763

F1 Score for this signal:
0.2817929039615397


In [58]:
printResults(y_ori,y4_pred_ori)

Confusion Matrix for this signal:
[[ 7300  2967  7419]
 [13658  4734 12879]
 [ 1613   481  1004]]
Accuracy for this signal:
0.2504658534242628
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.32      0.41      0.36     17686
           B       0.58      0.15      0.24     31271
           C       0.05      0.32      0.08      3098

    accuracy                           0.25     52055
   macro avg       0.32      0.30      0.23     52055
weighted avg       0.46      0.25      0.27     52055

F1 Score for this signal:
0.2722812099206781


In [59]:
from sklearn.naive_bayes import GaussianNB
gnb1 = GaussianNB()
gnb2 = GaussianNB()
gnb3 = GaussianNB()
gnb4 = GaussianNB()
gnb1.fit(X1_train, y1_train)

GaussianNB()

In [60]:
gnb2.fit(X2_train, y2_train)

GaussianNB()

In [61]:
gnb3.fit(X3_train, y3_train)

GaussianNB()

In [62]:
gnb4.fit(X4_train, y4_train)

GaussianNB()

In [63]:
make_model_and_save_as_pickle(gnb1,'./model_pickle_files/gnb/axial_force.pkl')
make_model_and_save_as_pickle(gnb2,'./model_pickle_files/gnb/bending_moment.pkl')
make_model_and_save_as_pickle(gnb3,'./model_pickle_files/gnb/channel2.pkl')
make_model_and_save_as_pickle(gnb4,'./model_pickle_files/gnb/spindle_power.pkl')

In [64]:
y1_pred = gnb1.predict(X1_test)
y1_pred_ori=gnb1.predict(x_1_ori)

In [65]:
y2_pred = gnb2.predict(X2_test)
y2_pred_ori=gnb2.predict(x_2_ori)

In [66]:
y3_pred = gnb3.predict(X3_test)
y3_pred_ori=gnb3.predict(x_3_ori)

In [67]:
y4_pred = gnb4.predict(X4_test)
y4_pred_ori=gnb4.predict(x_4_ori)

In [68]:
printResults(y1_test,y1_pred)

Confusion Matrix for this signal:
[[2556 1339 2300]
 [1182 3799 1378]
 [1868  886 3455]]
Accuracy for this signal:
0.5228374993337952
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.46      0.41      0.43      6195
           B       0.63      0.60      0.61      6359
           C       0.48      0.56      0.52      6209

    accuracy                           0.52     18763
   macro avg       0.52      0.52      0.52     18763
weighted avg       0.52      0.52      0.52     18763

F1 Score for this signal:
0.5223616577103857


In [69]:
printResults(y_ori,y1_pred_ori)

Confusion Matrix for this signal:
[[ 8305  4533  4848]
 [ 5755 18620  6896]
 [ 1038   588  1472]]
Accuracy for this signal:
0.5455191624243588
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.55      0.47      0.51     17686
           B       0.78      0.60      0.68     31271
           C       0.11      0.48      0.18      3098

    accuracy                           0.55     52055
   macro avg       0.48      0.51      0.45     52055
weighted avg       0.66      0.55      0.59     52055

F1 Score for this signal:
0.5895371471854163


In [70]:
printResults(y2_test,y2_pred)

Confusion Matrix for this signal:
[[3348 1876  971]
 [2688 2400 1271]
 [ 584  505 5120]]
Accuracy for this signal:
0.579225070617705
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.51      0.54      0.52      6195
           B       0.50      0.38      0.43      6359
           C       0.70      0.82      0.75      6209

    accuracy                           0.58     18763
   macro avg       0.57      0.58      0.57     18763
weighted avg       0.57      0.58      0.57     18763

F1 Score for this signal:
0.5682423914578976


In [71]:
printResults(y_ori,y2_pred_ori)

Confusion Matrix for this signal:
[[ 7224  6887  3575]
 [13246 11577  6448]
 [  315   463  2320]]
Accuracy for this signal:
0.4057439246950341
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.35      0.41      0.38     17686
           B       0.61      0.37      0.46     31271
           C       0.19      0.75      0.30      3098

    accuracy                           0.41     52055
   macro avg       0.38      0.51      0.38     52055
weighted avg       0.50      0.41      0.42     52055

F1 Score for this signal:
0.4225699293739686


In [72]:
printResults(y3_test,y3_pred)

Confusion Matrix for this signal:
[[3613 1000 1582]
 [2409 2899 1051]
 [1151  872 4186]]
Accuracy for this signal:
0.570164685817833
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.50      0.58      0.54      6195
           B       0.61      0.46      0.52      6359
           C       0.61      0.67      0.64      6209

    accuracy                           0.57     18763
   macro avg       0.58      0.57      0.57     18763
weighted avg       0.58      0.57      0.57     18763

F1 Score for this signal:
0.5676756259837248


In [73]:
printResults(y_ori,y3_pred_ori)

Confusion Matrix for this signal:
[[ 8749  4027  4910]
 [11693 14431  5147]
 [  406   833  1859]]
Accuracy for this signal:
0.48101046969551436
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.42      0.49      0.45     17686
           B       0.75      0.46      0.57     31271
           C       0.16      0.60      0.25      3098

    accuracy                           0.48     52055
   macro avg       0.44      0.52      0.42     52055
weighted avg       0.60      0.48      0.51     52055

F1 Score for this signal:
0.5119294990164123


In [74]:
printResults(y4_test,y4_pred)

Confusion Matrix for this signal:
[[4371  831  993]
 [3903 1300 1156]
 [1375  248 4586]]
Accuracy for this signal:
0.5466609817193413
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.45      0.71      0.55      6195
           B       0.55      0.20      0.30      6359
           C       0.68      0.74      0.71      6209

    accuracy                           0.55     18763
   macro avg       0.56      0.55      0.52     18763
weighted avg       0.56      0.55      0.52     18763

F1 Score for this signal:
0.517501825047642


In [75]:
printResults(y_ori,y4_pred_ori)

Confusion Matrix for this signal:
[[10561  4035  3090]
 [18899  6625  5747]
 [  645   604  1849]]
Accuracy for this signal:
0.36567092498319087
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.35      0.60      0.44     17686
           B       0.59      0.21      0.31     31271
           C       0.17      0.60      0.27      3098

    accuracy                           0.37     52055
   macro avg       0.37      0.47      0.34     52055
weighted avg       0.48      0.37      0.35     52055

F1 Score for this signal:
0.35325946717849277


In [76]:
from sklearn.linear_model import LogisticRegression


# instantiate the model
logreg1 = LogisticRegression(solver='liblinear', random_state=0)
logreg2 = LogisticRegression(solver='liblinear', random_state=0)
logreg3 = LogisticRegression(solver='liblinear', random_state=0)
logreg4 = LogisticRegression(solver='liblinear', random_state=0)


# fit the model
logreg1.fit(X1_train, y1_train)
logreg2.fit(X2_train, y2_train)
logreg3.fit(X3_train, y3_train)
logreg4.fit(X4_train, y4_train)

LogisticRegression(random_state=0, solver='liblinear')

In [77]:
make_model_and_save_as_pickle(logreg1,'./model_pickle_files/logreg/axial_force.pkl')
make_model_and_save_as_pickle(logreg2,'./model_pickle_files/logreg/bending_moment.pkl')
make_model_and_save_as_pickle(logreg3,'./model_pickle_files/logreg/channel2.pkl')
make_model_and_save_as_pickle(logreg4,'./model_pickle_files/logreg/spindle_power.pkl')

In [78]:
y1_pred = logreg1.predict(X1_test)
y1_pred_ori=logreg1.predict(x_1_ori)
y2_pred = logreg2.predict(X2_test)
y2_pred_ori=logreg2.predict(x_2_ori)
y3_pred = logreg3.predict(X3_test)
y3_pred_ori=logreg3.predict(x_3_ori)
y4_pred = logreg4.predict(X4_test)
y4_pred_ori=logreg4.predict(x_4_ori)

In [79]:
printResults(y1_test,y1_pred)

Confusion Matrix for this signal:
[[2496 1741 1958]
 [1088 4225 1046]
 [1926 1303 2980]]
Accuracy for this signal:
0.5170281937856419
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.45      0.40      0.43      6195
           B       0.58      0.66      0.62      6359
           C       0.50      0.48      0.49      6209

    accuracy                           0.52     18763
   macro avg       0.51      0.52      0.51     18763
weighted avg       0.51      0.52      0.51     18763

F1 Score for this signal:
0.5127079950143495


In [80]:
printResults(y_ori,y1_pred_ori)

Confusion Matrix for this signal:
[[ 7628  5515  4543]
 [ 5358 20808  5105]
 [  942   828  1328]]
Accuracy for this signal:
0.5717798482374412
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.55      0.43      0.48     17686
           B       0.77      0.67      0.71     31271
           C       0.12      0.43      0.19      3098

    accuracy                           0.57     52055
   macro avg       0.48      0.51      0.46     52055
weighted avg       0.65      0.57      0.60     52055

F1 Score for this signal:
0.6031083350077147


In [81]:
printResults(y2_test,y2_pred)

Confusion Matrix for this signal:
[[3133 1982 1080]
 [2583 2425 1351]
 [ 395  557 5257]]
Accuracy for this signal:
0.5764003624153919
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.51      0.51      0.51      6195
           B       0.49      0.38      0.43      6359
           C       0.68      0.85      0.76      6209

    accuracy                           0.58     18763
   macro avg       0.56      0.58      0.56     18763
weighted avg       0.56      0.58      0.56     18763

F1 Score for this signal:
0.5636447453449447


In [82]:
printResults(y_ori,y2_pred_ori)

Confusion Matrix for this signal:
[[ 6820  7009  3857]
 [12525 11815  6931]
 [  197   482  2419]]
Accuracy for this signal:
0.40445682451253484
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.35      0.39      0.37     17686
           B       0.61      0.38      0.47     31271
           C       0.18      0.78      0.30      3098

    accuracy                           0.40     52055
   macro avg       0.38      0.51      0.38     52055
weighted avg       0.50      0.40      0.42     52055

F1 Score for this signal:
0.4228085377664262


In [83]:
printResults(y3_test,y3_pred)

Confusion Matrix for this signal:
[[3510 1398 1287]
 [1986 3328 1045]
 [ 921 1244 4044]]
Accuracy for this signal:
0.5799712199541651
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.55      0.57      0.56      6195
           B       0.56      0.52      0.54      6359
           C       0.63      0.65      0.64      6209

    accuracy                           0.58     18763
   macro avg       0.58      0.58      0.58     18763
weighted avg       0.58      0.58      0.58     18763

F1 Score for this signal:
0.5794146386433214


In [84]:
printResults(y_ori,y3_pred_ori)

Confusion Matrix for this signal:
[[ 9226  4327  4133]
 [ 9795 16326  5150]
 [  579   640  1879]]
Accuracy for this signal:
0.5269618672557872
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.47      0.52      0.49     17686
           B       0.77      0.52      0.62     31271
           C       0.17      0.61      0.26      3098

    accuracy                           0.53     52055
   macro avg       0.47      0.55      0.46     52055
weighted avg       0.63      0.53      0.56     52055

F1 Score for this signal:
0.556986393597631


In [85]:
printResults(y4_test,y4_pred)

Confusion Matrix for this signal:
[[2667 2277 1251]
 [1681 3220 1458]
 [ 373  531 5305]]
Accuracy for this signal:
0.5964930981186377
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.56      0.43      0.49      6195
           B       0.53      0.51      0.52      6359
           C       0.66      0.85      0.75      6209

    accuracy                           0.60     18763
   macro avg       0.59      0.60      0.58     18763
weighted avg       0.59      0.60      0.58     18763

F1 Score for this signal:
0.5843910471617317


In [86]:
printResults(y_ori,y4_pred_ori)

Confusion Matrix for this signal:
[[ 6189  7468  4029]
 [ 8296 15622  7353]
 [  261   640  2197]]
Accuracy for this signal:
0.4612044952454135
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.42      0.35      0.38     17686
           B       0.66      0.50      0.57     31271
           C       0.16      0.71      0.26      3098

    accuracy                           0.46     52055
   macro avg       0.41      0.52      0.40     52055
weighted avg       0.55      0.46      0.49     52055

F1 Score for this signal:
0.48660398136702265


In [87]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier1 = RandomForestClassifier()
rf_classifier2 = RandomForestClassifier()
rf_classifier3 = RandomForestClassifier()
rf_classifier4 = RandomForestClassifier()
rf_classifier1.fit(X1_train, y1_train)


RandomForestClassifier()

In [88]:

rf_classifier2.fit(X2_train, y2_train)


RandomForestClassifier()

In [89]:

rf_classifier3.fit(X3_train, y3_train)


RandomForestClassifier()

In [90]:

rf_classifier4.fit(X4_train, y4_train)

RandomForestClassifier()

In [91]:
make_model_and_save_as_pickle(rf_classifier1,'./model_pickle_files/random_forest/axial_force.pkl')
make_model_and_save_as_pickle(rf_classifier2,'./model_pickle_files/random_forest/bending_moment.pkl')
make_model_and_save_as_pickle(rf_classifier3,'./model_pickle_files/random_forest/channel2.pkl')
make_model_and_save_as_pickle(rf_classifier4,'./model_pickle_files/random_forest/spindle_power.pkl')

In [92]:
y1_pred = rf_classifier1.predict(X1_test)
y1_pred_ori=rf_classifier1.predict(x_1_ori)
y2_pred = rf_classifier2.predict(X2_test)
y2_pred_ori=rf_classifier2.predict(x_2_ori)
y3_pred = rf_classifier3.predict(X3_test)
y3_pred_ori=rf_classifier3.predict(x_3_ori)
y4_pred = rf_classifier4.predict(X4_test)
y4_pred_ori=rf_classifier4.predict(x_4_ori)

In [93]:
printResults(y1_test,y1_pred)

Confusion Matrix for this signal:
[[2467 1466 2262]
 [1287 3705 1367]
 [2097 1013 3099]]
Accuracy for this signal:
0.49411074988008313
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.42      0.40      0.41      6195
           B       0.60      0.58      0.59      6359
           C       0.46      0.50      0.48      6209

    accuracy                           0.49     18763
   macro avg       0.49      0.49      0.49     18763
weighted avg       0.49      0.49      0.49     18763

F1 Score for this signal:
0.49399449319248245


In [94]:
printResults(y_ori,y1_pred_ori)

Confusion Matrix for this signal:
[[15694   937  1055]
 [ 1287 28617  1367]
 [  203   141  2754]]
Accuracy for this signal:
0.9041398520795313
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.91      0.89      0.90     17686
           B       0.96      0.92      0.94     31271
           C       0.53      0.89      0.67      3098

    accuracy                           0.90     52055
   macro avg       0.80      0.90      0.83     52055
weighted avg       0.92      0.90      0.91     52055

F1 Score for this signal:
0.9094042249987062


In [95]:
printResults(y2_test,y2_pred)

Confusion Matrix for this signal:
[[2921 2275  999]
 [2550 2525 1284]
 [ 598  546 5065]]
Accuracy for this signal:
0.5601982625379737
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.48      0.47      0.48      6195
           B       0.47      0.40      0.43      6359
           C       0.69      0.82      0.75      6209

    accuracy                           0.56     18763
   macro avg       0.55      0.56      0.55     18763
weighted avg       0.55      0.56      0.55     18763

F1 Score for this signal:
0.5507645474667603


In [96]:
printResults(y_ori,y2_pred_ori)

Confusion Matrix for this signal:
[[15564  1445   677]
 [ 2550 27437  1284]
 [   70    69  2959]]
Accuracy for this signal:
0.8829123042935357
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.86      0.88      0.87     17686
           B       0.95      0.88      0.91     31271
           C       0.60      0.96      0.74      3098

    accuracy                           0.88     52055
   macro avg       0.80      0.90      0.84     52055
weighted avg       0.90      0.88      0.89     52055

F1 Score for this signal:
0.8861493580770621


In [97]:
printResults(y3_test,y3_pred)

Confusion Matrix for this signal:
[[3846 1098 1251]
 [1560 4454  345]
 [ 869  310 5030]]
Accuracy for this signal:
0.7104407610723232
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.61      0.62      0.62      6195
           B       0.76      0.70      0.73      6359
           C       0.76      0.81      0.78      6209

    accuracy                           0.71     18763
   macro avg       0.71      0.71      0.71     18763
weighted avg       0.71      0.71      0.71     18763

F1 Score for this signal:
0.7100697766315387


In [98]:
printResults(y_ori,y3_pred_ori)

Confusion Matrix for this signal:
[[16309   657   720]
 [ 1560 29366   345]
 [   92    55  2951]]
Accuracy for this signal:
0.934127365286716
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.91      0.92      0.92     17686
           B       0.98      0.94      0.96     31271
           C       0.73      0.95      0.83      3098

    accuracy                           0.93     52055
   macro avg       0.87      0.94      0.90     52055
weighted avg       0.94      0.93      0.94     52055

F1 Score for this signal:
0.9353652378921575


In [99]:
printResults(y4_test,y4_pred)

Confusion Matrix for this signal:
[[4103 1563  529]
 [1555 4473  331]
 [ 372  232 5605]]
Accuracy for this signal:
0.7557959814528593
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.68      0.66      0.67      6195
           B       0.71      0.70      0.71      6359
           C       0.87      0.90      0.88      6209

    accuracy                           0.76     18763
   macro avg       0.75      0.76      0.75     18763
weighted avg       0.75      0.76      0.75     18763

F1 Score for this signal:
0.7544315611758883


In [100]:
printResults(y_ori,y4_pred_ori)

Confusion Matrix for this signal:
[[16107  1240   339]
 [ 1555 29385   331]
 [   77    85  2936]]
Accuracy for this signal:
0.9303236960906733
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.91      0.91      0.91     17686
           B       0.96      0.94      0.95     31271
           C       0.81      0.95      0.88      3098

    accuracy                           0.93     52055
   macro avg       0.89      0.93      0.91     52055
weighted avg       0.93      0.93      0.93     52055

F1 Score for this signal:
0.930696245368392


In [101]:
from sklearn.ensemble import GradientBoostingClassifier
gb_classifier1 = GradientBoostingClassifier()
gb_classifier2 = GradientBoostingClassifier()
gb_classifier3 = GradientBoostingClassifier()
gb_classifier4 = GradientBoostingClassifier()
gb_classifier1.fit(X1_train, y1_train)

GradientBoostingClassifier()

In [102]:
gb_classifier2.fit(X2_train, y2_train)

GradientBoostingClassifier()

In [103]:
gb_classifier3.fit(X3_train, y3_train)

GradientBoostingClassifier()

In [104]:
gb_classifier4.fit(X4_train, y4_train)

GradientBoostingClassifier()

In [105]:
make_model_and_save_as_pickle(gb_classifier1,'./model_pickle_files/gradient_boosting/axial_force.pkl')
make_model_and_save_as_pickle(gb_classifier2,'./model_pickle_files/gradient_boosting/bending_moment.pkl')
make_model_and_save_as_pickle(gb_classifier3,'./model_pickle_files/gradient_boosting/channel2.pkl')
make_model_and_save_as_pickle(gb_classifier4,'./model_pickle_files/gradient_boosting/spindle_power.pkl')

In [106]:
y1_pred = gb_classifier1.predict(X1_test)
y1_pred_ori=gb_classifier1.predict(x_1_ori)
y2_pred = gb_classifier2.predict(X2_test)
y2_pred_ori=gb_classifier2.predict(x_2_ori)
y3_pred = gb_classifier3.predict(X3_test)
y3_pred_ori=gb_classifier3.predict(x_3_ori)
y4_pred = gb_classifier4.predict(X4_test)
y4_pred_ori=gb_classifier4.predict(x_4_ori)

In [107]:
printResults(y1_test,y1_pred)

Confusion Matrix for this signal:
[[2483 1391 2321]
 [1069 3877 1413]
 [1788  943 3478]]
Accuracy for this signal:
0.5243297980067153
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.46      0.40      0.43      6195
           B       0.62      0.61      0.62      6359
           C       0.48      0.56      0.52      6209

    accuracy                           0.52     18763
   macro avg       0.52      0.52      0.52     18763
weighted avg       0.52      0.52      0.52     18763

F1 Score for this signal:
0.5227186490394707


In [108]:
printResults(y_ori,y1_pred_ori)

Confusion Matrix for this signal:
[[ 8126  4678  4882]
 [ 5232 19047  6992]
 [  954   620  1524]]
Accuracy for this signal:
0.551282297569878
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.57      0.46      0.51     17686
           B       0.78      0.61      0.68     31271
           C       0.11      0.49      0.18      3098

    accuracy                           0.55     52055
   macro avg       0.49      0.52      0.46     52055
weighted avg       0.67      0.55      0.60     52055

F1 Score for this signal:
0.5950289737707107


In [109]:
printResults(y2_test,y2_pred)

Confusion Matrix for this signal:
[[2799 2364 1032]
 [2078 2899 1382]
 [ 460  425 5324]]
Accuracy for this signal:
0.5874327133187657
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.52      0.45      0.49      6195
           B       0.51      0.46      0.48      6359
           C       0.69      0.86      0.76      6209

    accuracy                           0.59     18763
   macro avg       0.57      0.59      0.58     18763
weighted avg       0.57      0.59      0.58     18763

F1 Score for this signal:
0.5760301551515374


In [110]:
printResults(y_ori,y2_pred_ori)

Confusion Matrix for this signal:
[[ 5649  8144  3893]
 [ 9667 14700  6904]
 [  251   401  2446]]
Accuracy for this signal:
0.437902218807031
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.36      0.32      0.34     17686
           B       0.63      0.47      0.54     31271
           C       0.18      0.79      0.30      3098

    accuracy                           0.44     52055
   macro avg       0.39      0.53      0.39     52055
weighted avg       0.51      0.44      0.46     52055

F1 Score for this signal:
0.45722019792855373


In [111]:
printResults(y3_test,y3_pred)

Confusion Matrix for this signal:
[[3692 1069 1434]
 [1592 4358  409]
 [ 729  353 5127]]
Accuracy for this signal:
0.7022864147524384
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.61      0.60      0.60      6195
           B       0.75      0.69      0.72      6359
           C       0.74      0.83      0.78      6209

    accuracy                           0.70     18763
   macro avg       0.70      0.70      0.70     18763
weighted avg       0.70      0.70      0.70     18763

F1 Score for this signal:
0.7005199967568874


In [112]:
printResults(y_ori,y3_pred_ori)

Confusion Matrix for this signal:
[[10078  3702  3906]
 [ 7649 21631  1991]
 [  330   395  2373]]
Accuracy for this signal:
0.654730573431947
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.56      0.57      0.56     17686
           B       0.84      0.69      0.76     31271
           C       0.29      0.77      0.42      3098

    accuracy                           0.65     52055
   macro avg       0.56      0.68      0.58     52055
weighted avg       0.71      0.65      0.67     52055

F1 Score for this signal:
0.6723912682420847


In [113]:
printResults(y4_test,y4_pred)

Confusion Matrix for this signal:
[[3727 1810  658]
 [1324 4623  412]
 [ 355  279 5575]]
Accuracy for this signal:
0.7421521078718755
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.69      0.60      0.64      6195
           B       0.69      0.73      0.71      6359
           C       0.84      0.90      0.87      6209

    accuracy                           0.74     18763
   macro avg       0.74      0.74      0.74     18763
weighted avg       0.74      0.74      0.74     18763

F1 Score for this signal:
0.7389291361846225


In [114]:
printResults(y_ori,y4_pred_ori)

Confusion Matrix for this signal:
[[ 8396  7516  1774]
 [ 6209 22975  2087]
 [  278   558  2262]]
Accuracy for this signal:
0.6461050811641533
Classification Report for this signal:
              precision    recall  f1-score   support

           A       0.56      0.47      0.52     17686
           B       0.74      0.73      0.74     31271
           C       0.37      0.73      0.49      3098

    accuracy                           0.65     52055
   macro avg       0.56      0.65      0.58     52055
weighted avg       0.66      0.65      0.65     52055

F1 Score for this signal:
0.6473032351468037
